Repository MicrosoftDocs/sql-docs.ru-ru, pull requests merged in 2020-04, with the labels that each got.

#75 Update not-equal-to-transact-sql-traditional.md
  docs/t-sql/language-elements/not-equal-to-transact-sql-traditional.md
Labels: Accepted, Linguistic Suggestion

#78 Update import-data-from-excel-to-sql.md
  docs/relational-databases/import-export/import-data-from-excel-to-sql.md
Labels: Accepted, Linguistic Suggestion

#71 Improve TOC translation
  docs/toc.yml
Labels: Accepted, Linguistic Suggestion

#77 Update hardware-and-software-requirements-for-installing-sql-server.md
  docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#79 Update control-transaction-durability.md
  docs/relational-databases/logs/control-transaction-durability.md
Labels: Accepted, Linguistic Suggestion

#80 Update index.yml
  docs/sql-server/index.yml
Labels: Linguistic Suggestion, Partially Accepted

#81 formatting issue
  docs/sql-server/index.yml
Labels: Accepted, Linguistic Suggestion
